# You can build any language by using Docker images from Docker Hub.
image: 
  name: immcantation
  username: $USERNAME
  password: $PASSWORD
  email: $EMAIL

pipelines:
  default:
    - step:
        script:
          - R CMD build .
          - R CMD check *.tar.gz
