image: 
  name: kleinstein/immcantation:test

pipelines:
  default:
    - step:
        script:
          - sed -i '/test/ d' .Rbuildignore
          - R CMD build .
          - R CMD check *.tar.gz --as-cran --run-donttest --timings
