site_name: alakazam
repo_url: https://bitbucket.org/kleinstein/alakazam
theme: readthedocs
markdown_extensions:
  - def_list
  - sane_lists
  - smarty
  - toc:
      permalink: True
docs_dir: 'docs'
pages:
  - 'About':
    - 'Introduction': index.md
    - 'Download & Installation': install.md
    - 'Package Overview': topics/alakazam.md
    - 'Release Notes': news.md
    - 'Related Projects': projects.md
  - 'Vignettes':
    - 'Amino acid physicochemical property analysis': vignettes/AminoAcids-Vignette.md
    - 'Analysis of clonal abundance and diversity': vignettes/Diversity-Vignette.md
    - 'Reconstruction of Ig lineage trees': vignettes/Lineage-Vignette.md
    - 'Topology analysis of lineage trees': vignettes/Topology-Vignette.md
  - 'Help Topics':
    - 'File I/O':
      - topics/readChangeoDb.md
      - topics/writeChangeoDb.md
    - 'Sequence Cleaning and Manipulation':
      - topics/collapseDuplicates.md
      - topics/maskSeqEnds.md
      - topics/maskSeqGaps.md
      - topics/translateDNA.md
      - topics/isValidAASeq.md
    - 'Lineage Reconstruction':
      - topics/buildPhylipLineage.md
      - topics/makeChangeoClone.md
      - topics/ChangeoClone-class.md
    - 'Lineage Topology Analysis':
      - topics/getMRCA.md
      - topics/getPathLengths.md
      - topics/permuteLabels.md
      - topics/summarizeSubtrees.md
      - topics/tableEdges.md
      - topics/testEdges.md
      - topics/testMRCA.md
      - topics/plotEdgeTest.md
      - topics/plotMRCATest.md
      - topics/plotSubtrees.md
      - topics/EdgeTest-class.md
      - topics/MRCATest-class.md
    - 'Diversity Analysis':
      - topics/calcCoverage.md
      - topics/calcDiversity.md
      - topics/countClones.md
      - topics/estimateAbundance.md
      - topics/rarefyDiversity.md
      - topics/testDiversity.md
      - topics/plotAbundance.md
      - topics/plotDiversityCurve.md
      - topics/DiversityCurve-class.md
      - topics/DiversityTest-class.md
    - 'Ig and TCR Sequence Annotation':
      - topics/countGenes.md
      - topics/sortGenes.md
      - topics/getSegment.md
      - topics/extractVRegion.md
    - 'Sequence Distance Calculation':
      - topics/getAAMatrix.md
      - topics/getDNAMatrix.md
      - topics/seqDist.md
      - topics/seqEqual.md
      - topics/pairwiseDist.md
      - topics/pairwiseEqual.md
    - 'Amino Acid Propertes':
      - topics/aminoAcidProperties.md
      - topics/countPatterns.md
      - topics/aliphatic.md
      - topics/bulk.md
      - topics/charge.md
      - topics/gravy.md
      - topics/polar.md
    - 'Miscellaneous':
      - topics/translateStrings.md
      - topics/makeTempDir.md
      - topics/gridPlot.md
      - topics/stoufferMeta.md
    - 'Data and Constants':
      - topics/ExampleDb.md
      - topics/ExampleTrees.md
      - topics/ABBREV_AA.md
      - topics/IUPAC_CODES.md
      - topics/DEFAULT_COLORS.md
      - topics/IMGT_REGIONS.md
      
